name: Restard
main: reload/Loader
version: 2.0.9
api: [1.12.0]
load: STARTUP
author: SebiCraftLP Unlimetet Developer
description: Server neu start.
website: https://DevMatter/usr/sebicraftlp/lib/Plugin/221
commands:
 r:
  description: "Restart Zeit"
  permission: asr.command.asr
 restart:
  description: "Restart Status"
  permission: asr.command.restart
permissions:
 asr.command.asr:
  description: "Usage: /Restart <value>"
  default: op
 asr.command.restart:
  description: "Usage: /Restart"
  default: op
